services:
  - type: web
    name: hwaseon-url
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DOMAIN
        value: https://hwaseon-url.com
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
    autoDeploy: true 